# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-15 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=10)),
                ('feedback_text', models.CharField(max_length=200)),
                ('mail_text', models.CharField(max_length=200)),
                ('user_text', models.CharField(max_length=200)),
                ('answer_date', models.DateTimeField()),
            ],
        ),
    ]
